[package]
name = "openx-wpf-control"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
openx-engine-godot = { path = "../../engines/godot" }
openx-engine-ogre = { path = "../../engines/ogre" }
openx-engine-opengl = { path = "../../engines/opengl" }
openx-engine-sdl = { path = "../../engines/sdl" }
openx-engine-unity = { path = "../../engines/unity" }
