// PORT-SOURCE: Core/GameX/BlizzardProtoDatabase.cs
// PORT-SHA: 733f96e831880639
// PORT-STATUS: done
//
// NOT PORTED — 4,986 lines of protobuf compiler output.
//
// The file opens with:
//
//     // <auto-generated>
//     //     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     //     source: proto_database.proto
//
// So the artefact to port is not this file, it is `proto_database.proto`. Run
// `prost-build` over that schema from a `build.rs` and the Rust equivalent is
// generated the same way the C# was — which also keeps it correct when the
// schema changes, rather than drifting.
//
// One catch: **`proto_database.proto` is not in this repository.** The generated
// C# is committed without its source schema, so the schema has to be recovered
// before either language can regenerate. It is recoverable: the serialized
// `FileDescriptorProto` is embedded in the committed output as
// `ProtoDatabaseReflection.Descriptor`, and `prost` can consume a
// `FileDescriptorSet` directly. Extracting it is a better first step than
// hand-porting 4,986 generated lines.
//
// Kept as a file so the 1:1 mapping holds and `sync-check.sh` tracks drift.
