<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <Optimize>False</Optimize>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <Optimize>True</Optimize>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\..\docs\Engines\Sdl\Readme.md" Link="Readme.md" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\OpenX\dotnet\Engines\OpenX.Engine.Mg\OpenX.Engine.Mg.csproj" />
    <ProjectReference Include="..\..\..\OpenX\dotnet\Engines\OpenX.Engine.Sdl\OpenX.Engine.Sdl.csproj" />
    <ProjectReference Include="..\..\Core\GameX\GameX.csproj" />
  </ItemGroup>

</Project>
