[package]
name = "gamex-engine-stride"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
gamex = { path = "../../core/gamex" }
openx-engine-stride = { path = "../../../OpenX/rust/engines/stride" }
openx-sfx = { path = "../../../OpenX/rust/sfx/sfx" }
