from __future__ import annotations
import os
from gamex.families.Xbox.formats.binary import Binary_Xnb
from .GameData import *

def register() -> None:
    pass
    # Binary_Xnb.add(Binary_Xnb.TypeReader[str]('BmFont.XmlSourceReader', 'String', lambda r: r.readLV7UString()))
    
    # Binary_Xnb.add(Binary_Xnb.TypeReader[ModFarmType]('ModFarmType', 'StardewValley.GameData.ModFarmType', lambda r: ModFarmType()))
    # Binary_Xnb.add(Binary_Xnb.TypeReader[ModLanguage]('ModLanguage', 'StardewValley.GameData.ModLanguage', lambda r: ModLanguage()))
    # Binary_Xnb.add(Binary_Xnb.TypeReader[ModWallpaperOrFlooring]('ModWallpaperOrFlooring', 'StardewValley.GameData.ModWallpaperOrFlooring', lambda r: ModWallpaperOrFlooring()))
    # Binary_Xnb.add(Binary_Xnb.TypeReader[AudioCueData]('AudioCueData', 'StardewValley.GameData.AudioCueData', lambda r: AudioCueData()))
    # Binary_Xnb.add(Binary_Xnb.TypeReader[BigCraftables.BigCraftableData]('ModLanguage', 'StardewValley.GameData.BigCraftables.BigCraftableData', lambda r: BigCraftables.BigCraftableData()))
    # Binary_Xnb.add(Binary_Xnb.TypeReader[Buffs.BuffData]('Buffs.BuffData', 'StardewValley.GameData.Buffs.BuffData', lambda r: Buffs.BuffData()))
    # Binary_Xnb.add(Binary_Xnb.TypeReader[Buffs.BuffAttributesData]('Buffs.BuffAttributesData', 'StardewValley.GameData.Buffs.BuffAttributesData', lambda r: Buffs.BuffAttributesData()))

    # Binary_Xnb.add(Binary_Xnb.TypeReader[Buildings.BuildingData]('Buildings.BuildingData', 'StardewValley.GameData.Buildings.BuildingData', lambda r: Buildings.BuildingData()))
    # Binary_Xnb.add(Binary_Xnb.TypeReader[Characters.CharacterData]('Characters.CharacterData', 'StardewValley.GameData.Characters.CharacterData', lambda r: Characters.CharacterData()))
    # Binary_Xnb.add(Binary_Xnb.TypeReader[Movies.ConcessionItemData]('Movies.ConcessionItemData', 'StardewValley.GameData.Movies.ConcessionItemData', lambda r: Movies.ConcessionItemData()))
    # Binary_Xnb.add(Binary_Xnb.TypeReader[Movies.ConcessionTaste]('Movies.ConcessionTaste', 'StardewValley.GameData.Movies.ConcessionTaste', lambda r: Movies.ConcessionTaste()))
    # Binary_Xnb.add(Binary_Xnb.TypeReader[Crops.CropData]('Crops.CropData', 'StardewValley.GameData.Crops.CropData', lambda r: Crops.CropData()))
    # Binary_Xnb.add(Binary_Xnb.TypeReader[FarmAnimals.FarmAnimalData]('FarmAnimals.FarmAnimalData', 'StardewValley.GameData.FarmAnimals.FarmAnimalData', lambda r: FarmAnimals.FarmAnimalData()))
    # Binary_Xnb.add(Binary_Xnb.TypeReader[Fences.FenceData]('Fences.FenceData', 'StardewValley.GameData.Fences.FenceData', lambda r: Fences.FenceData()))
    # Binary_Xnb.add(Binary_Xnb.TypeReader[FishPonds.FishPondData]('FishPonds.FishPondData', 'StardewValley.GameData.FishPonds.FishPondData', lambda r: FishPonds.FishPondData()))
    # Binary_Xnb.add(Binary_Xnb.TypeReader[FloorsAndPaths.FloorPathData]('FloorsAndPaths.FloorPathData', 'StardewValley.GameData.FloorsAndPaths.FloorPathData', lambda r: FloorsAndPaths.FloorPathData()))
    # Binary_Xnb.add(Binary_Xnb.TypeReader[FruitTrees.FruitTreeData]('FruitTrees.FruitTreeData', 'StardewValley.GameData.FruitTrees.FruitTreeData', lambda r: FruitTrees.FruitTreeData()))
    # Binary_Xnb.add(Binary_Xnb.TypeReader[GarbageCans.GarbageCanData]('GarbageCans.GarbageCanData', 'StardewValley.GameData.GarbageCans.GarbageCanData', lambda r: GarbageCans.GarbageCanData()))
    # Binary_Xnb.add(Binary_Xnb.TypeReader[GiantCrops.GiantCropData]('GiantCrops.GiantCropData', 'StardewValley.GameData.GiantCrops.GiantCropData', lambda r: GiantCrops.GiantCropData()))
    # Binary_Xnb.add(Binary_Xnb.TypeReader[HomeRenovations.HomeRenovation]('HomeRenovations.HomeRenovation', 'StardewValley.GameData.HomeRenovations.HomeRenovation', lambda r: HomeRenovations.HomeRenovation()))
    # Binary_Xnb.add(Binary_Xnb.TypeReader[IncomingPhoneCallData]('IncomingPhoneCallData', 'StardewValley.GameData.IncomingPhoneCallData', lambda r: IncomingPhoneCallData()))
    # Binary_Xnb.add(Binary_Xnb.TypeReader[JukeboxTrackData]('JukeboxTrackData', 'StardewValley.GameData.JukeboxTrackData', lambda r: JukeboxTrackData()))
    # Binary_Xnb.add(Binary_Xnb.TypeReader[LocationContexts.LocationContextData]('LocationContexts.LocationContextData', 'StardewValley.GameData.LocationContexts.LocationContextData', lambda r: LocationContexts.LocationContextData()))
    # Binary_Xnb.add(Binary_Xnb.TypeReader[Locations.LocationData]('Locations.LocationData', 'StardewValley.GameData.Locations.LocationData', lambda r: Locations.LocationData()))
    # Binary_Xnb.add(Binary_Xnb.TypeReader[LostItem]('LostItem', 'StardewValley.GameData.LostItem', lambda r: GameData.LostItem()))
    # Binary_Xnb.add(Binary_Xnb.TypeReader[Machines.MachineData]('Machines.MachineData', 'StardewValley.GameData.Machines.MachineData', lambda r: Machines.MachineData()))
    # Binary_Xnb.add(Binary_Xnb.TypeReader[MakeoverOutfits.MakeoverOutfit]('MakeoverOutfits.MakeoverOutfit', 'StardewValley.GameData.MakeoverOutfits.MakeoverOutfit', lambda r: MakeoverOutfits.MakeoverOutfit()))
    # Binary_Xnb.add(Binary_Xnb.TypeReader[MannequinData]('MannequinData', 'StardewValley.GameData.MannequinData', lambda r: MannequinData()))
    # Binary_Xnb.add(Binary_Xnb.TypeReader[Minecarts.MinecartNetworkData]('Minecarts.MinecartNetworkData', 'StardewValley.GameData.Minecarts.MinecartNetworkData', lambda r: Minecarts.MinecartNetworkData()))
    # Binary_Xnb.add(Binary_Xnb.TypeReader[MonsterSlayerQuestData]('MonsterSlayerQuestData', 'StardewValley.GameData.MonsterSlayerQuestData', lambda r: MonsterSlayerQuestData()))
    # Binary_Xnb.add(Binary_Xnb.TypeReader[Movies.MovieData]('Movies.MovieData', 'StardewValley.GameData.Movies.MovieData', lambda r: Movies.MovieData()))
    # Binary_Xnb.add(Binary_Xnb.TypeReader[Movies.MovieCharacterReaction]('Movies.MovieCharacterReaction', 'StardewValley.GameData.Movies.MovieCharacterReaction', lambda r: Movies.MovieCharacterReaction()))
    # Binary_Xnb.add(Binary_Xnb.TypeReader[Museum.MuseumRewards]('Museum.MuseumRewards', 'StardewValley.GameData.Museum.MuseumRewards', lambda r: Museum.MuseumRewards()))
    # Binary_Xnb.add(Binary_Xnb.TypeReader[Objects.ObjectData]('Objects.ObjectData', 'StardewValley.GameData.Objects.ObjectData', lambda r: Objects.ObjectData()))
    # Binary_Xnb.add(Binary_Xnb.TypeReader[Pants.PantsData]('Pants.PantsData', 'StardewValley.GameData.Pants.PantsData', lambda r: Pants.PantsData()))
    # Binary_Xnb.add(Binary_Xnb.TypeReader[PassiveFestivalData]('PassiveFestivalData', 'StardewValley.GameData.PassiveFestivalData', lambda r: PassiveFestivalData()))
    # Binary_Xnb.add(Binary_Xnb.TypeReader[Pets.PetData]('Pets.PetData', 'StardewValley.GameData.Pets.PetData', lambda r: Pets.PetData()))
    # Binary_Xnb.add(Binary_Xnb.TypeReader[Powers.PowersData]('Powers.PowersData', 'StardewValley.GameData.Powers.PowersData', lambda r: Powers.PowersData()))
    # Binary_Xnb.add(Binary_Xnb.TypeReader[Bundles.RandomBundleData]('Bundles.RandomBundleData', 'StardewValley.GameData.Bundles.RandomBundleData', lambda r: Bundles.RandomBundleData()))
    # Binary_Xnb.add(Binary_Xnb.TypeReader[Shirts.ShirtData]('Shirts.ShirtData', 'StardewValley.GameData.Shirts.ShirtData', lambda r: Shirts.ShirtData()))
    # Binary_Xnb.add(Binary_Xnb.TypeReader[Shops.ShopData]('Shops.ShopData', 'StardewValley.GameData.Shops.ShopData', lambda r: Shops.ShopData()))
    # Binary_Xnb.add(Binary_Xnb.TypeReader[SpecialOrders.SpecialOrderData]('SpecialOrders.SpecialOrderData', 'StardewValley.GameData.SpecialOrders.SpecialOrderData', lambda r: SpecialOrders.SpecialOrderData()))
    # Binary_Xnb.add(Binary_Xnb.TypeReader[Crafting.TailorItemRecipe]('Crafting.TailorItemRecipe', 'StardewValley.GameData.Crafting.TailorItemRecipe', lambda r: Crafting.TailorItemRecipe()))
    # Binary_Xnb.add(Binary_Xnb.TypeReader[Tools.ToolData]('Tools.ToolData', 'StardewValley.GameData.Tools.ToolData', lambda r: Tools.ToolData()))
    # Binary_Xnb.add(Binary_Xnb.TypeReader[TriggerActionData]('TriggerActionData', 'StardewValley.GameData.TriggerActionData', lambda r: TriggerActionData()))
    # Binary_Xnb.add(Binary_Xnb.TypeReader[TrinketData]('TrinketData', 'StardewValley.GameData.TrinketData', lambda r: TrinketData()))
    # Binary_Xnb.add(Binary_Xnb.TypeReader[Weapons.WeaponData]('Weapons.WeaponData', 'StardewValley.GameData.Weapons.WeaponData', lambda r: Weapons.WeaponData()))
    # Binary_Xnb.add(Binary_Xnb.TypeReader[Weddings.WeddingData]('Weddings.WeddingData', 'StardewValley.GameData.Weddings.WeddingData', lambda r: Weddings.WeddingData()))
    # Binary_Xnb.add(Binary_Xnb.TypeReader[WildTrees.WildTreeData]('WildTrees.WildTreeData', 'StardewValley.GameData.WildTrees.WildTreeData', lambda r: WildTrees.WildTreeData()))
    # Binary_Xnb.add(Binary_Xnb.TypeReader[WorldMaps.WorldMapRegionData]('WorldMaps.WorldMapRegion', 'StardewValley.GameData.WorldMaps.WorldMapRegionData', lambda r: WorldMaps.WorldMapRegionData()))

