[package]
name = "gamex-engine-opengl"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
gamex = { path = "../../core/gamex" }
gamex-gamebryo = { path = "../../families/gamebryo" }
openx-engine-opengl = { path = "../../../OpenX/rust/engines/opengl" }
