<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DefineConstants>TRACE;ID_DEDICATED_</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Sfx\OpenX.Sfx.Al\OpenX.Sfx.Al.csproj" />
    <ProjectReference Include="..\..\Sfx\OpenX.Sfx.Ogg\OpenX.Sfx.Ogg.csproj" />
    <ProjectReference Include="..\OpenX.XGngine\OpenX.XGngine.csproj" />
  </ItemGroup>

</Project>
