[package]
name = "openx-engine-opengl"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
openx = { path = "../../core/openx" }
openx-gfx = { path = "../../gfx/gfx" }
openx-gfx-egin = { path = "../../gfx/gfx-egin" }
glam = { workspace = true }
glow = "0.14"
