[package]
name = "gamex-app-explorer"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
gamex-all = { path = "../../core/all" }
gamex-cig-explorer = { path = "../../families/cig-explorer" }
gamex-engine-godot = { path = "../../engines/engine-godot" }
gamex-engine-o3de = { path = "../../engines/engine-o3de" }
gamex-engine-ogre = { path = "../../engines/engine-ogre" }
gamex-engine-opengl = { path = "../../engines/engine-opengl" }
gamex-engine-sdl = { path = "../../engines/engine-sdl" }
gamex-engine-stride = { path = "../../engines/engine-stride" }
gamex-engine-unity = { path = "../../engines/engine-unity" }
gamex-engine-unreal = { path = "../../engines/engine-unreal" }
